### ISSUE TITLE
Improvement: import meta data file (csv file) in mitobench

### ISSUE THREAD

**Issue by haansi** [mitobench/mitoBench#67]
Would be great to open the meta data file (CSV + FASTA) directly in mitobench

**Comment by haansi** [comment]
Subsequently the validation tool could be integrated directly in mitobench

**Comment by JudithNeukamm** [comment]
Opening a csv file should already be possible (if the first two rows are formatted correctly). Did you have any problems?

Integration the validation tool into mitoBench is a great idea, I will work on that :)

**Comment by JudithNeukamm** [comment]
The validation tool is integrated into mitoBench now.
