### ISSUE TITLE
Suggestion: Undefined entries

### ISSUE THREAD

**Issue by haansi** [mitobench/mitoBench#69]
Should we try to avoid/remove the "undefined" entries? Makes it harder to handle/read the data.

**Comment by JudithNeukamm** [comment]
No problem. What would you suggest using instead? Or leaving it blank?

**Comment by haansi** [comment]
Leaving blank should be ok - depends if the information is important. Do we need to differentiate between empty and undefined? If so, we could use the ?

**Comment by JudithNeukamm** [comment]
Hm, at the moment, I automatically set 'undefined' if I get a blank field. I think there is no need to differentiate between empty or undefined. In the end, the information is the same: no information available... 
I will change the 'undefined' fields to blank fields
