### ISSUE TITLE
Mitobench-1.4-beta.jar throws class not found exception: JavaFX

### ISSUE THREAD

**Issue by subwaystation** [mitobench/mitoBench#77]
Hi  @JudithNeukamm 
I tried to run mitoBench, but I ran into the following issue:
```
[heumos@wave Downloads]$ java -jar MitoBench-1.4-beta.jar 
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at MitoBenchStarter.lambda$main$0(MitoBenchStarter.java:17)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 more
```
Even after installing [java-openjfx](https://www.archlinux.org/packages/extra/x86_64/java-openjfx/), the error persists.

Any ideas?

**Comment by JudithNeukamm** [comment]
Hi Simon, 
which java version are you using?
It works fine with java8, as far as I know, the installation of JavaFX with higher java version is a bit more tricky. 

Best. Judith

**Comment by subwaystation** [comment]
Hi Judith,
I am using Java12:

```
heumos@wave ~/g/GenGraph> java --version
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode)
```
I guess you build Mitobench with Java8 in mind. There JavaFX is still integrated into the JDK.
However, I think since Java9 or so?! it is not part of the JDK anymore.
So you need to ship it directly with your application, if I understood everything correctly: https://stackoverflow.com/questions/16868446/javafx-exception-in-thread-main-java-lang-noclassdeffounderror-javafx-applica

What do you think?
Best,
Simon

**Comment by JudithNeukamm** [comment]
That's definitely a point of my todo list, but not implemented at the moment. it might be possible to set the javafx version as an argument. Have you tried something like this: https://openjfx.io/openjfx-docs/#install-javafx ?

**Comment by JudithNeukamm** [comment]
That's definitely a point of my todo list, but not implemented at the moment. Until it's done, you might have to run mitoBench with java8.

**Comment by subwaystation** [comment]
I see. Thanks!

**Comment by JudithNeukamm** [comment]
Hi Simon, 
I'm currently working on a version that can be opened with Java11 as well. For now, please use this work around: 
to run mitoBench with Java11, please download the JavaFX SDK (https://gluonhq.com/products/javafx/) and start the mitoBench jar file via this command: 

_java --module-path <path/to/javafx-sdk/lib> --add-modules=javafx.controls -jar MitoBench-1.6-beta.jar_

Please let me know if it works with Java12 as well. 
Best, Judith

**Comment by subwaystation** [comment]
Hi Judith,

now it works!

However:
[heumos@wave Downloads]$ java --module-path javafx-sdk-11.0.2/lib  
--add-modules=javafx.controls -jar MitoBench-1.6-beta.jar
Exception in thread "JavaFX Application Thread"  
java.lang.NoClassDefFoundError: javafx/scene/web/WebView
    at view.menus.HelpMenu.lambda$add$1(HelpMenu.java:48)
    at  
javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:465)
    at  
javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
    at  
javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
    at  
javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at  
javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at  
javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at  
javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
    at  
javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
    at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    at  
javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
    at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
    at  
javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native  
Method)
    at  
javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javafx.scene.web.WebView
    at  
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at  
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 43 more
Exception in thread "JavaFX Application Thread"  
java.lang.NoClassDefFoundError: javafx/scene/web/WebView
    at view.menus.HelpMenu.lambda$add$1(HelpMenu.java:48)
    at  
javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:465)
    at  
javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
    at  
javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
    at  
javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at  
javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at  
javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at  
javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at  
javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at  
javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
    at  
javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
    at  
javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
    at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    at  
javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    at  
javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
    at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
    at  
javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native  
Method)
    at  
javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javafx.scene.web.WebView
    at  
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at  
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 43 more

When I click on Help + About Mitobench.

Best,

Simon

On 12/3/19 4:11 PM, Judith Neukamm wrote:
> Hi Simon,
> I'm currently working on a version that can be opened with Java11 as  
> well. For now, please use this work around:
> to run mitoBench with Java11, please download the JavaFX SDK  
> (https://gluonhq.com/products/javafx/) and start the mitoBench jar  
> file via this command:
>
> _java --module-path <path/to/javafx-sdk/lib>  
> --add-modules=javafx.controls -jar MitoBench-1.6-beta.jar_
>
> Please let me know if it works with Java12 as well.
> Best, Judith
>
-- 
M.Sc. Simon Heumos
Bioinformatics Research Scientist

Quantitative Biology Center (QBiC)
Eberhard Karls Universität Tübingen
Auf der Morgenstelle 10, D-72076 Tübingen

phone: +49-7071-29-70296
email: simon.heumos@qbic.uni-tuebingen.de

https://qbic.life


-- 
Simon Heumos
Project Manager

Quantitative Biology Center (QBiC)
Eberhard Karls Universität Tübingen
Auf der Morgenstelle 10, D-72076 Tübingen

phone: +49-7071-29-70296
email: simon.heumos@qbic.uni-tuebingen.de

https://qbic.life

*** follow us ***
https://facebook.com/qbic.tuebingen
https://twitter.com/qbic_tue

**Comment by JudithNeukamm** [comment]
I know. That's why I deleted my last post ;)

**Comment by subwaystation** [comment]
Ups, did not see that :P

**Comment by JudithNeukamm** [comment]
mitoBench is now updated to Java11 and will be available with the next release. 
I am closing this issue, but please let me know if it does not work.

**Comment by JudithNeukamm** [comment]
Hi Kay, 
also die Version 1.7-beta läuft nur unter Java8.
Kam die Fehlermeldung direkt nach dem Starten, oder nachdem du etwas geklickt hast?
Grüsse, Judith

**Comment by JudithNeukamm** [comment]
Und die Release, die unter Java11 läuft, kommt erst noch.

Der Fehler scheint MacOS spezifisch zu sein, ich werd mich mal schlau machen.

**Comment by nieselt** [comment]
Des wegen frage ich nach, da du ja rumgeschickt hattest, dass es jetzt ein java11-release gibt, aber es nur java8 bislang im git ist.

Diese Version: Ja es läuft unter mac unter Java 8 und wirft diese Meldungen, wenn man was klickt.

VG,

Kay
