### ISSUE TITLE
PGDSPider freezes mitoBench 1.7

### ISSUE THREAD

**Issue by haansi** [mitobench/mitoBench#83]
Hi Judith,

Similar to #82 also in mitoBench Version 1.7, trying to export files with  PGDSpider results in an freeze of mitobench - no error message though.

**Comment by JudithNeukamm** [comment]
Hi Hansi

PGDSpider had to be removed with the latest pre-release (https://github.com/mitobench/mitoBench/releases/tag/v1.8-beta) because it is not compatible with Java11. 
I will not pursue the issue further, as mitoBench is continued exclusively for Java11 (for now :) ).

Cheers
Judith
