### ISSUE TITLE
Export all data (currently n=23920) in Excel format

### ISSUE THREAD

**Issue by haansi** [mitobench/mitoBench#84]
Hi, some minor issues:

Export of all data (n=23920) in XLSX format results in an Java Heap Space error. Works for CSV  and TSV - each 412MB.
When increasing the heap space with "java-jar  -Xmx8G" the file gets written after a while, (XLSX 29MB) - warning appears: 

Warning: Could not get charToByteConverterClass! - and data gets exportet

**Comment by JudithNeukamm** [comment]
Hi Hansi

I updated the EXCEL reader and writer in version 1.8-beta (https://github.com/mitobench/mitoBench/releases/tag/v1.8-beta). This issue should be solved now. 
I'm closing this issue. Please feel free to open it again if the error persists. 

Cheers
Judith
